type Status = {
  [key: number]: string;
};
//audit log
export const PACKAGE_UPDATE_TYPE_RECIPIENT = 1;
export const PACKAGE_UPDATE_TYPE_PHONENUMBER = 2;
export const PACKAGE_UPDATE_TYPE_ADDRESS = 3;
export const PACKAGE_UPDATE_TYPE_ADDRESS2 = 13;
export const PACKAGE_UPDATE_TYPE_CITY = 4;
export const PACKAGE_UPDATE_TYPE_STATECODE = 5;
export const PACKAGE_UPDATE_TYPE_ZIPCODE = 6;
export const PACKAGE_UPDATE_TYPE_COUNTRYCODE = 7;
export const PACKAGE_UPDATE_TYPE_WEIGHT = 8;
export const PACKAGE_UPDATE_TYPE_VOLUME = 9;
export const PACKAGE_UPDATE_TYPE_NOTE = 10;
export const PACKAGE_UPDATE_TYPE_SERVICE = 11;
export const PACKAGE_UPDATE_TYPE_DETAIL = 12;
export const PACKAGE_UPDATE_TYPE_LABEL = 13;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_COVID = 14;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_OUTSIZE = 15;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_FIXVOLUME = 16;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_FIXWEIGHT = 17;
export const PACKAGE_UPDATE_EXTRAFEE_EDIT_ORDER = 19;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_REFUND = 20;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_OTHER = 21;
export const PACKAGE_CHECK_ADDRESS_TYPE = 22;
export const PACKAGE_IGNORE_ADDRESS_TYPE = 23;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_RESHIP = 24;
export const PACKAGE_UPDATE_TYPE_ORDER_NUMBER = 25;
export const PACKAGE_UPDATE_TYPE_PRODUCT = 26;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_PEAK = 27;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_CANCEL_LABEL = 28;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_OVERSIZE = 29;
export const PACKAGE_UPDATE_ADRESS_EXCEED_PACKAGE = 31;
export const PACKAGE_UPDATE_RETURN_PACKAGE = 32;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_BATTERY = 33;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_INSURED = 34;
export const PACKAGE_UPDATE_EXTRAFEE_TYPE_SERVICE = 35;

export const CHANGE_PACKAGE_TYPE: Status = {
  [PACKAGE_UPDATE_TYPE_RECIPIENT]: "Người nhận",
  [PACKAGE_UPDATE_TYPE_PHONENUMBER]: "Số điện thoại người nhận",
  [PACKAGE_UPDATE_TYPE_ADDRESS]: "Địa chỉ người nhận",
  [PACKAGE_UPDATE_TYPE_ADDRESS2]: "Địa chỉ phụ người nhận",
  [PACKAGE_UPDATE_TYPE_CITY]: "Thành phố",
  [PACKAGE_UPDATE_TYPE_STATECODE]: "Mã vùng",
  [PACKAGE_UPDATE_TYPE_ZIPCODE]: "Mã bưu điện",
  [PACKAGE_UPDATE_TYPE_COUNTRYCODE]: "Mã quốc gia",
  [PACKAGE_UPDATE_TYPE_WEIGHT]: "Trọng lượng",
  [PACKAGE_UPDATE_TYPE_VOLUME]: "Kích thước (DxRxC)",
  [PACKAGE_UPDATE_TYPE_NOTE]: "Yêu cầu khi giao",
  [PACKAGE_UPDATE_TYPE_SERVICE]: "Dịch vụ",
  [PACKAGE_UPDATE_TYPE_DETAIL]: "Chi tiết hàng hóa",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_COVID]: "Covid",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_OUTSIZE]: "Quá cỡ",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_FIXVOLUME]: "Sửa kích thước",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_FIXWEIGHT]: "Sửa trọng lượng",
  [PACKAGE_UPDATE_EXTRAFEE_EDIT_ORDER]: "Sửa đơn",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_REFUND]: "Hoàn tiền",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_OTHER]: "Phí phát sinh khác",
  [PACKAGE_CHECK_ADDRESS_TYPE]: "Xác nhận xóa cảnh báo địa chỉ không hợp lệ",
  [PACKAGE_IGNORE_ADDRESS_TYPE]: "Bỏ qua kiểm tra địa chỉ bằng API",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_RESHIP]: "Reship",
  [PACKAGE_UPDATE_TYPE_ORDER_NUMBER]: "Mã đơn hàng",
  [PACKAGE_UPDATE_TYPE_PRODUCT]: "",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_PEAK]: "",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_CANCEL_LABEL]: "Hủy Label",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_OVERSIZE]: "Phí quá thể tích",
  [PACKAGE_UPDATE_ADRESS_EXCEED_PACKAGE]: "Phí sửa địa chỉ",
  [PACKAGE_UPDATE_RETURN_PACKAGE]: "Return",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_BATTERY]: "Phụ phí pin",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_INSURED]: "Phí bảo hiểm",
  [PACKAGE_UPDATE_EXTRAFEE_TYPE_SERVICE]: "Phụ phí kích thước",
};

export const PACKAGE_STATUS_DEACTIVATE = 0;
export const PACKAGE_STATUS_CREATED = 1;
export const PACKAGE_STATUS_PENDING_PICKUP = 2;
export const PACKAGE_STATUS_RE_PENDING_PICKUP = 3;
export const PACKAGE_STATUS_PICKED = 10;
export const PACKAGE_STATUS_WAREHOUSE_LABELED = 11;
export const PACKAGE_STATUS_WAREHOUSE_IN_CONTAINER = 12;
export const PACKAGE_STATUS_WAREHOUSE_IN_SHIPMENT = 13;
export const PACKAGE_STATUS_WAREHOUSE_EXPORT = 14;
export const PACKAGE_STATUS_IN_TRANSIT = 30;
export const PACKAGE_STATUS_DELIVERED = 60;
export const PACKAGE_STATUS_RETURNED = 40;
export const PACKAGE_STATUS_CANCELLED = 50;
export const PACKAGE_STATUS_EXPIRED = 70;
export const PACKAGE_STATUS_RESHIP = 80;
export const PACKAGE_STATUS_UNDELIVERED = 90;
export const PACKAGE_STATUS_ARCHIVED = 55;
export const PACKAGE_DELIVERY_LOG_TYPE_RESHIP = 80;

export const DELIVER_LOG_PACKAGE: Status = {
  [PACKAGE_STATUS_IN_TRANSIT]: "Arriving at international airport to go abroad",
  [PACKAGE_STATUS_PENDING_PICKUP]:
    "Shipping label created, LionBay awaiting item",
  [PACKAGE_STATUS_RE_PENDING_PICKUP]:
    "Shipping label created, LionBay awaiting item",
  [PACKAGE_STATUS_PICKED]: "Accepted at LionBay Processing	Center",
  [PACKAGE_STATUS_CANCELLED]: "Label canceled",
  [PACKAGE_STATUS_DELIVERED]: "Delivered",
  [PACKAGE_STATUS_WAREHOUSE_EXPORT]: "Departed from LionBay Processing Center",
  [PACKAGE_DELIVERY_LOG_TYPE_RESHIP]: "Reship package",
};

export const EXTRA_FEE_CANCEL_LABEL = 13;
export const PACKAGE_STATUS_CREATED_TEXT = "pending";
export const PACKAGE_REFUND_COMPLETE = 2;
